name: cfps
description: CFPS Banking app.

publish_to: "none"

version: 0.1.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"
  flutter: ">=3.3.10 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  auto_route: ^5.0.4
  flutter_bloc: ^8.1.1
  bloc: ^8.1.0
  bloc_test: ^9.1.0
  flutter_hooks: ^0.18.5+1
  injectable: ^2.1.0
  get_it: ^7.2.0
  freezed: ^2.2.0
  freezed_annotation: ^2.2.0
  retrofit: ^3.3.1
  logger: ^1.1.0
  intl: ^0.17.0
  dartz: ^0.10.1
  json_serializable: ^6.5.4
  mockito: ^5.3.2
  retrofit_generator: ^4.2.0
  flutter_secure_storage: ^7.0.1
  pretty_dio_logger: ^1.1.1
  json_annotation: ^4.7.0
  dio: ^4.0.6
  skeletons: ^0.0.3
  google_fonts: ^3.0.1
  flutter_svg: ^1.1.6
  gap: ^2.0.1
  package_info_plus: ^3.0.2
  fluttertoast: ^8.1.2
  flag: ^6.0.0
  flutter_multi_formatter: ^2.10.1
  flutter_native_splash: ^2.2.16
  custom_refresh_indicator: ^2.0.1

  #kyc
  flutter_idensic_mobile_sdk_plugin: ^1.22.2


  # Firebase
  firebase_core: ^2.4.0
  firebase_crashlytics: ^3.0.7

  shared_preferences: ^2.0.16


dev_dependencies:
  build_runner: ^2.3.0
  injectable_generator: ^2.1.3
  auto_route_generator: ^5.0.2
  intl_utils: ^2.7.0

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/svg/
    - assets/images/png/

flutter_intl:
  enabled: true
  class_name: Translation
  arb_dir: lib/app/utils/translations/l10n
  output_dir: lib/app/utils/translations/generated

flutter_native_splash:
  image: assets/splash.png
  color: "#ffffff"
